CREATE DATABASE IF NOT EXISTS otumami_database;

USE otumami_database;

CREATE TABLE IF NOT EXISTS UserTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ChatRecipeTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Food TEXT NOT NULL,
    Recipe TEXT NOT NULL,
    Drink VARCHAR(100) NOT NULL,
    LikeRecipe BOOLEAN NOT NULL,

    FOREIGN KEY (UserId) REFERENCES UserTable(Id)
);